# Generated by Django 4.2.5 on 2023-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_of_preparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageofpreparation',
            name='step',
            field=models.IntegerField(default=0, verbose_name='Номер шага'),
        ),
    ]
