# Generated by Django 4.2.5 on 2023-09-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
    ]
