# Generated by Django 4.2.5 on 2023-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_alter_unit_name'),
        ('ingredient', '0003_remove_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'unit')},
        ),
    ]
