# Generated by Django 4.2.5 on 2023-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', verbose_name='Описание'),
        ),
    ]
